# Site settings
name: Jussi Linnala
email: jussi.linnala@gmail.com
canonical_url: https://linnala.github.io
keywords: "”Mis sie tarvitset oikei hyvvää miestä? Täs siul on sellane!”"
skills: "IT, teknologia, liikkeenjohto"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jussi-linnala-4057846/
#  - title: medium
#    url: https://medium.com/@sielunahjo
#  - title: twitter
#    url: https://twitter.com/sielunahjo
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D2D7D9
  primary-rgb: "210, 215, 217"
  secondary: D2D7D9
  secondary-dark: 102742
  section-tout: F26863



# Build settings
markdown: kramdown
permalink: pretty
